/* Autogenerated by hxtools bin2c */
#ifndef THOMAS_H
#define THOMAS_H 1

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char bin2c_thomas_bin[493136];
extern const float (* thomas)[2];

#ifdef __cplusplus
} /* extern "C" */
#endif


#endif /* THOMAS_H */
